# Project Euler - Problem 2
# 
# Even Fibonacci numbers
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def p2(max_number):

    first_number = 1
    second_number = 2
    current_number = first_number + second_number
    sum_of_even_number = 2

    while current_number <= max_number:
        if current_number % 2 == 0:
            sum_of_even_number += current_number
        first_number = second_number
        second_number = current_number
        current_number = first_number + second_number

    return sum_of_even_number

if __name__ == "__main__":
    print(p2(4000000))
